
const state={products:[],cart:JSON.parse(localStorage.getItem('motrivaCart')||'[]'),wishlist:JSON.parse(localStorage.getItem('motrivaWishlist')||'[]')};
const save=()=>{localStorage.setItem('motrivaCart',JSON.stringify(state.cart));localStorage.setItem('motrivaWishlist',JSON.stringify(state.wishlist));updateCount()};
const updateCount=()=>{const e=document.getElementById('cartCount');if(e)e.textContent=state.cart.reduce((a,b)=>a+b.qty,0)};
const addToCart=id=>{const x=state.cart.find(i=>i.id===id);x?x.qty++:state.cart.push({id,qty:1});save();toast('Added to cart')};
const toggleWish=id=>{state.wishlist=state.wishlist.includes(id)?state.wishlist.filter(x=>x!==id):[...state.wishlist,id];save();toast(state.wishlist.includes(id)?'Saved to wishlist':'Removed from wishlist')};
const toast=m=>{let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1300)};
const card=p=>`<article class="card"><div class="badge">${p.id%4===0?'Best Seller':p.id%4===1?'New':'Popular'}</div><button class="wish" onclick="toggleWish(${p.id})">♡</button><a class="pic" href="product.html?id=${p.id}"><img src="${p.image}" alt="${p.name}" loading="lazy"></a><div class="rating">★★★★★ <span class="muted">(${p.reviews})</span></div><h3>${p.name}</h3><div class="price">$${p.price.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</div><button class="add" onclick="addToCart(${p.id})">Add to Cart</button></article>`;
async function load(){const r=await fetch('products.json');state.products=await r.json();renderShop();renderProduct();renderCart();renderWishlist();setupFilters()}
function renderShop(){const g=document.getElementById('shopGrid');if(!g)return;const q=(document.getElementById('shopSearch')?.value||new URLSearchParams(location.search).get('search')||'').toLowerCase();const cat=document.getElementById('catFilter')?.value||new URLSearchParams(location.search).get('cat')||'';const sort=document.getElementById('sort')?.value||'featured';let a=state.products.filter(p=>(!q||(p.name+' '+p.category+' '+p.description).toLowerCase().includes(q))&&(!cat||p.category===cat));if(sort==='price-low')a.sort((x,y)=>x.price-y.price);if(sort==='price-high')a.sort((x,y)=>y.price-x.price);if(sort==='name')a.sort((x,y)=>x.name.localeCompare(y.name));g.innerHTML=a.map(card).join('')}
function setupFilters(){const c=document.getElementById('catFilter');if(c){[...new Set(state.products.map(p=>p.category))].sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;c.appendChild(o)});const q=new URLSearchParams(location.search).get('cat');if(q)c.value=q}['shopSearch','catFilter','sort'].forEach(id=>document.getElementById(id)?.addEventListener('input',renderShop));document.getElementById('search')?.addEventListener('keydown',e=>{if(e.key==='Enter')location.href='shop.html?search='+encodeURIComponent(e.target.value)})}
function renderProduct(){const e=document.getElementById('productDetail');if(!e)return;const id=Number(new URLSearchParams(location.search).get('id')||0),p=state.products.find(x=>x.id===id)||state.products[0];e.innerHTML=`<div style="display:grid;grid-template-columns:1fr 1fr;gap:32px"><div class="pic" style="height:560px;background:#ece8df;border:1px solid #2d302f"><img src="${p.image}" alt="${p.name}" style="width:100%;height:100%;object-fit:contain;padding:25px"></div><div><div class="eyebrow">${p.category}</div><h1 class="page-title">${p.name}</h1><div class="rating">★★★★★ (${p.reviews})</div><div class="price" style="font-size:28px;margin:14px 0">$${p.price.toFixed(2)}</div><p style="color:#aaa9a2;line-height:1.8">${p.description}</p><button class="btn" onclick="addToCart(${p.id})">Add to Cart</button><a class="btn alt" href="contact.html">Ask Support</a><div style="margin-top:25px;padding:18px;background:#111313;border:1px solid #2b2e2d;border-radius:6px"><strong>MOTRIVA Support</strong><p style="color:#aaa9a2">+1 (800) 555-0186 · support@motrivamotoparts.com</p></div></div></div>`}
function renderCart(){const e=document.getElementById('cartPage');if(!e)return;if(!state.cart.length){e.innerHTML='<p style="color:#aaa9a2">Your cart is empty.</p><a class="btn" href="shop.html">Shop Parts</a>';return}let t=0;e.innerHTML=state.cart.map(i=>{const p=state.products.find(x=>x.id===i.id);if(!p)return'';t+=p.price*i.qty;return `<div style="display:flex;gap:15px;align-items:center;background:#111313;padding:14px;margin:9px 0;border:1px solid #2b2e2d;border-radius:6px"><img src="${p.image}" style="width:90px;height:90px;object-fit:contain;background:#ece8df;border-radius:5px"><div style="flex:1"><strong>${p.name}</strong><div style="color:#aaa9a2">Qty ${i.qty}</div></div><div>$${(p.price*i.qty).toFixed(2)} <button onclick="state.cart=state.cart.filter(x=>x.id!==${i.id});save();renderCart()">Remove</button></div></div>`}).join('')+`<h2>Total: $${t.toFixed(2)}</h2><button class="btn" onclick="toast('Checkout demo ready')">Checkout</button>`}
function renderWishlist(){const e=document.getElementById('wishlistPage');if(!e)return;const a=state.products.filter(p=>state.wishlist.includes(p.id));e.innerHTML=a.length?`<div class="grid">${a.map(card).join('')}</div>`:'<p style="color:#aaa9a2">No saved parts yet.</p>'}
updateCount();load();
